name: Deploy Java App to VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Install dependencies (optional but ensures Maven setup is correct)
    - name: Install dependencies
      run: mvn install

    # Build the Java application (produces the JAR file)
    - name: Build JAR
      run: mvn package

    # Copy the JAR file to the VM
    - name: Copy JAR to VM
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        source: target/*.jar
        target: /home/${{ secrets.VM_USERNAME }}/app.jar

    # Run the Java app on the VM
    - name: Run Java App on VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        timeout: 120m   # Increase timeout to 120 minutes
        port: 22
        script: |
            echo "Updating system..."
            sudo apt update && sudo apt install -y openjdk-17-jdk

            echo "Killing any running Java app..."
            pkill -f "java -jar /home/${{ secrets.VM_USERNAME }}/app.jar" || true

            echo "Starting Java app with PM2..."
            pm2 start /home/${{ secrets.VM_USERNAME }}/app.jar --name java-app --watch --log /home/${{ secrets.VM_USERNAME }}/app.log --output /home/${{ secrets.VM_USERNAME }}/pm2-out.log --error /home/${{ secrets.VM_USERNAME }}/pm2-error.log

            # Save PM2 process list so it can restart after reboot
            pm2 save

            # Make sure PM2 is running the app correctly
            pm2 list
            pm2 status

            echo "Java app started successfully with PM2."
      env:
            JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
            JAVA_HOME_17_X64: /usr/lib/jvm/java-17-openjdk-amd64

    # Build the Docker image
    - name: Build Docker Image
      run: docker build -t java-app:latest .

    # Save Docker image as a tarball
    - name: Save Docker Image as tar
      run: docker save java-app:latest -o java-app.tar

    # Copy Docker image tarball to the VM
    - name: Copy Docker Image to VM
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        source: java-app.tar
        target: /tmp/java-app.tar

    # SSH into the VM and deploy Docker container
    - name: Deploy Docker App to VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          docker load < /tmp/java-app.tar
          docker stop java-app || true
          docker rm java-app || true
          docker run -d --name java-app -p 8080:8080 java-app:latest
